apiVersion: v1
kind: Service
metadata:
  name: helixworks
  namespace: helixworks
spec:
  selector:
    app.kubernetes.io/name: helixworks
  ports:
    - name: http
      port: 80
      targetPort: http

