apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../base, secrets.yaml]
patches:
  - target: { kind: Deployment }
    patch: |-
      - { op: replace, path: /spec/replicas, value: 1 }
configMapGenerator:
  - { name: forge-environment, namespace: zheta-forge, behavior: merge, literals: [ENVIRONMENT=local] }
