apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helixworks
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ZGTR/helixworks-kubernetes-lab.git
    targetRevision: master
    path: gitops/apps/helixworks/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: helixworks
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

