apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata: { name: forge-local, namespace: argocd }
spec:
  generators:
    - list: { elements: [{ cluster: in-cluster, url: "https://kubernetes.default.svc" }] }
  template:
    metadata: { name: forge-local }
    spec:
      project: default
      source: { repoURL: "https://github.com/ZGTR/zheta-kubernetes-lab.git", targetRevision: master, path: gitops/apps/forge/overlays/local }
      destination: { server: '{{url}}', namespace: zheta-forge }
      syncPolicy: { automated: { prune: true, selfHeal: true }, syncOptions: [CreateNamespace=true] }
